/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gf.vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author sanarrda
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private VistaEleccion vistaEleccion;
    private AudioInputStream audioInputStream;
    private Clip clip;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        setFrame();
        this.vistaEleccion = new VistaEleccion(this, true);
        try {
            this.audioInputStream = AudioSystem.getAudioInputStream(new File("./src/main/java/com/gf/recursos/InicioAplicacion.wav").getAbsoluteFile());
            this.clip = AudioSystem.getClip();
            this.clip.open(this.audioInputStream);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setFrame() {
        this.setLayout(new BorderLayout());
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.imagenMemory.setIcon(new ImageIcon("./src/main/java/com/gf/recursos/Memory_principal.png"));
        this.botonAjustes.setIcon(new ImageIcon("./src/main/java/com/gf/recursos/configuracion.png"));
        this.setBackground(Color.black);
        this.setTitle("Memory");
    }

    public void setSonido(boolean on) throws LineUnavailableException, UnsupportedAudioFileException, IOException {

        if (on == true) {
            clip.start();
        }
        if (on == false) {
            clip.stop();
        }

    }

    public JButton getBotonAjustes() {
        return botonAjustes;
    }

    public JButton getBotonComenzar() {
        return botonComenzar;
    }

    public JButton getBotonRanking() {
        return botonRanking;
    }

    public VistaEleccion getVistaEleccion() {
        return vistaEleccion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenMemory = new javax.swing.JLabel();
        botonRanking = new javax.swing.JButton();
        botonComenzar = new javax.swing.JButton();
        botonAjustes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        botonRanking.setText("Ranking");

        botonComenzar.setText("Comenzar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 394, Short.MAX_VALUE)
                .addComponent(botonAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(imagenMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonComenzar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(botonRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(imagenMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonComenzar)
                .addGap(21, 21, 21)
                .addComponent(botonRanking)
                .addGap(12, 12, 12)
                .addComponent(botonAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAjustes;
    private javax.swing.JButton botonComenzar;
    private javax.swing.JButton botonRanking;
    private javax.swing.JLabel imagenMemory;
    // End of variables declaration//GEN-END:variables
}
